-- This query calculates the total revenue generated by each product.

SELECT
    products.Description AS Product,
    products.FaceValue,
    COUNT(transactionledger.EntryID) AS TimesIssued,
    SUM(transactionledger.Amount) AS TotalRevenue
FROM Products
LEFT JOIN TransactionLedger
    ON products.ProductID = transactionledger.ProductID
GROUP BY products.Description, products.FaceValue;
